doctrine:
    dbal:
        default_connection: life_saver
        connections:
            life_saver:
                host:     '%env(resolve:MYSQL_LIFE_SAVER_HOST)%'
                port:     '%env(resolve:MYSQL_PORT)%'
                dbname:   '%env(resolve:MYSQL_LIFE_SAVER_DATABASE)%'
                user:     '%env(resolve:MYSQL_USER)%'
                password: '%env(resolve:MYSQL_PASSWORD)%'
                driver: 'pdo_mysql'
                server_version: '%env(resolve:MYSQL_VERSION)%'
                charset:  UTF8
    orm:
        auto_generate_proxy_classes: true
        entity_managers:
            life_saver:
                connection: life_saver
                mappings:
                    BodyTracker:
                        is_bundle: false
                        type: yml
                        dir: '%kernel.project_dir%/config/doctrine/BodyTracker'
                        prefix: 'App\Domain\DTO\BodyTracker'
                    MindTracker:
                        is_bundle: false
                        type: yml
                        dir: '%kernel.project_dir%/config/doctrine/MindTracker'
                        prefix: 'App\Domain\DTO\MindTracker'
                    HydrationTracker:
                        is_bundle: false
                        type: yml
                        dir: '%kernel.project_dir%/config/doctrine/HydrationTracker'
                        prefix: 'App\Domain\DTO\HydrationTracker'
                    ActivityTracker:
                        is_bundle: false
                        type: yml
                        dir: '%kernel.project_dir%/config/doctrine/ActivityTracker'
                        prefix: 'App\Domain\DTO\ActivityTracker'
                    TheLibrarian:
                        is_bundle: false
                        type: yml
                        dir: '%kernel.project_dir%/config/doctrine/TheLibrarian'
                        prefix: 'App\Domain\DTO\TheLibrarian'
                    TheCoach:
                        is_bundle: false
                        type: yml
                        dir: '%kernel.project_dir%/config/doctrine/TheCoach'
                        prefix: 'App\Domain\DTO\TheCoach'
                    Common:
                        is_bundle: false
                        type: yml
                        dir: '%kernel.project_dir%/config/doctrine/Common'
                        prefix: 'App\Domain\DTO'