doctrine:
    dbal:
        default_connection: body_tracker
        connections:
            body_tracker:
                host:     '%env(resolve:MYSQL_BODY_TRACKER_HOST)%'
                port:     '%env(resolve:MYSQL_PORT)%'
                dbname:   '%env(resolve:MYSQL_BODY_TRACKER_DATABASE)%'
                user:     '%env(resolve:MYSQL_USER)%'
                password: '%env(resolve:MYSQL_PASSWORD)%'
                driver: 'pdo_mysql'
                server_version: '%env(resolve:MYSQL_VERSION)%'
                charset:  UTF8
    orm:
        auto_generate_proxy_classes: true
        entity_managers:
            body_tracker:
                connection: body_tracker
                mappings:
                    BodyTracker:
                        is_bundle: false
                        type: yml
                        dir: '%kernel.project_dir%/config/doctrine/BodyTracker'
                        prefix: 'App\Domain\DTO\BodyTracker'
                    Common:
                        is_bundle: false
                        type: yml
                        dir: '%kernel.project_dir%/config/doctrine/Common'
                        prefix: 'App\Domain\DTO'