public:
    resource:
        path: ../src/Infrastructure/Controller/Public
        namespace: App\Infrastructure\Controller\Public
    type: attribute

player:
    resource:
        path: ../src/Infrastructure/Controller/Player
        namespace: App\Infrastructure\Controller\Player
    type: attribute
    prefix: /player


admin:
    resource:
        path: ../src/Infrastructure/Controller/Admin
        namespace: App\Infrastructure\Controller\Admin
    type: attribute
    prefix: /admin
