App\Domain\DTO\User\UserSummaryDTO:
  type: entity
  repositoryClass: App\Infrastructure\Repository\User\UserSummaryRepository
  table: '`USER_SUMMARY`'
  indexes:
    name_index:
      columns: [ userId ]

  id:
    id:
      type: integer
      generator:
        strategy: AUTO

  fields:
    activityTracker:
      type: json
      nullable: false
      unique: false
    bodyTracker:
      type: json
      nullable: false
      unique: false
    hydrationTracker:
      type: json
      nullable: false
      unique: false
    theCoach:
      type: json
      nullable: false
      unique: false
    theLibrarian:
      type: json
      nullable: false
      unique: false

  manyToOne:
    user:
      targetEntity: UserDTO
      joinColumn:
        name: userId
        referencedColumnName: id
