App\Domain\DTO\ActivityTracker\ActivityTypeDTO:
  type: entity
  repositoryClass: App\Infrastructure\Repository\ActivityTracker\ActivityTypeDTORepository
  table: '`ACTIVITY_TYPE`'

  id:
    id:
      type: integer
      generator:
        strategy: AUTO

  fields:
    title:
      type: string
      nullable: false
      unique: false

  manyToOne:
    activityCategory:
      targetEntity: ActivityCategoryDTO
      joinColumn:
        name: categotyId
        referencedColumnName: id