App\Domain\DTO\ActivityTracker\ActivityDTO:
  type: entity
  repositoryClass: App\Infrastructure\Repository\ActivityTracker\ActivityRepository
  table: '`ACTIVITY`'

  id:
    id:
      type: integer
      generator:
        strategy: AUTO

  fields:
    title:
      type: text
      nullable: false
      unique: false
    userId:
      type: integer
      nullable: false
      unique: false

  manyToOne:
    activityType:
      targetEntity: ActivityTypeDTO
      joinColumn:
        name: typeId
        referencedColumnName: id
        nullable: true