App\Domain\DTO\TheCoach\ExerciseDTO:
  type: entity
  repositoryClass: App\Infrastructure\Repository\TheCoach\ExerciseDTORepository
  table: '`EXERCISE`'

  id:
    id:
      type: integer
      generator:
        strategy: AUTO

  fields:
    targetReps:
      type: integer
      nullable: true
      unique: false
    targetWeight:
      type: integer
      nullable: true
      unique: false
    targetDuration:
      type: integer
      nullable: true
      unique: false
    targetDistance:
      type: integer
      nullable: true
      unique: false

    completedReps:
      type: integer
      nullable: true
      unique: false
    completedWeight:
      type: integer
      nullable: true
      unique: false
    completedDuration:
      type: integer
      nullable: true
      unique: false
    completedDistance:
      type: integer
      nullable: true
      unique: false

    restDuration:
      type: integer
      nullable: true
      unique: false

  manyToOne:
    workout:
      targetEntity: WorkoutDTO
      inversedBy: exercises
      joinColumn:
        name: workoutId
        referencedColumnName: id
        nullable: false
    movement:
      targetEntity: MovementDTO
      joinColumn:
        name: movementId
        referencedColumnName: id
        nullable: false