App\Domain\DTO\TheCoach\RoutineDTO:
  type: entity
  repositoryClass: App\Infrastructure\Repository\TheCoach\RoutineDTORepository
  table: '`ROUTINE`'

  id:
    id:
      type: integer
      generator:
        strategy: AUTO

  fields:
    title:
      type: string
      nullable: false
      unique: true

  oneToMany:
    movements:
      targetEntity: RoutineToMovementDTO
      mappedBy: routine
