App\Domain\DTO\TheLibrarian\BookAuthorDTO:
  type: entity
  repositoryClass: App\Infrastructure\Repository\TheLibrarian\BookAuthorRepository
  table: '`BOOK_AUTHOR`'

  id:
    id:
      type: integer
      generator:
        strategy: AUTO

  fields:
    fullName:
      type: string
      nullable: false
      unique: false
    openLibraryKey:
      type: string
      nullable: false
      unique: true